# 打包依赖阶段使用golang作为基础镜像
FROM golang:1.18 as builder

WORKDIR /app

COPY . .

# CGO_ENABLED禁用cgo 然后指定OS等，并go build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -o mxclub-mini ./apps/mxclub-mini/


RUN mkdir publish && cp mxclub-mini publish

# 运行阶段指定scratch作为基础镜像
FROM alpine:latest

# 将上一个阶段publish文件夹下的所有文件复制进来
COPY --from=builder /app/publish .

EXPOSE 8000

CMD ["sh", "-c", "./mxclub-mini -f /config/mxclub-mini.yml > /logs/app.$(date +'%Y.%m.%d').log 2>&1"]
