name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Include Test Workflow
        uses: ./.github/workflows/test.yml

  deploy_job:
    name: Deploy Job
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Include Deploy Workflow
        uses: ./.github/workflows/deploy.yml